# Generated by Django 5.2.17 on 2026-10-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_rating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(default='eur', max_length=3),
        ),
        migrations.AlterField(
            model_name='payout',
            name='currency',
            field=models.CharField(default='eur', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='currency',
            field=models.CharField(default='eur', max_length=3),
        ),
    ]
