# Generated by Django 5.2.17 on 2026-09-22 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('sku', models.CharField(blank=True, default='', max_length=40)),
                ('price_cents', models.PositiveIntegerField(help_text='Unit price in the smallest currency unit (e.g. 4999 = $49.99).')),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('image_url', models.URLField(blank=True, default='')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('fulfilled', 'Fulfilled')], db_index=True, default='pending', max_length=16)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('shipping_name', models.CharField(blank=True, default='', max_length=120)),
                ('shipping_line1', models.CharField(blank=True, default='', max_length=200)),
                ('shipping_line2', models.CharField(blank=True, default='', max_length=200)),
                ('shipping_city', models.CharField(blank=True, default='', max_length=120)),
                ('shipping_state', models.CharField(blank=True, default='', max_length=120)),
                ('shipping_postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('shipping_country', models.CharField(blank=True, default='', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
