# Generated by Django 5.2.17 on 2026-10-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='eur', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='eur', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_cents',
            field=models.PositiveIntegerField(help_text='Unit price in the smallest currency unit (e.g. 4999 = €49.99).'),
        ),
    ]
