# Generated by Django 5.2.17 on 2026-10-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_product_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=280),
                ),
                (
                    "estimate",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Shown to shoppers, e.g. "2-4 business days".',
                        max_length=80,
                    ),
                ),
                (
                    "price_cents",
                    models.PositiveIntegerField(
                        default=0, help_text="Delivery fee in cents. 0 means free."
                    ),
                ),
                (
                    "free_over_cents",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Delivery is free when the items total at least this many cents.",
                        null=True,
                    ),
                ),
                (
                    "countries",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated ISO country codes. Blank means every store shipping country.",
                        max_length=400,
                    ),
                ),
                (
                    "requires_address",
                    models.BooleanField(
                        default=True,
                        help_text="Untick for local pickup so checkout does not ask for an address.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "price_cents", "name"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_name",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="store.deliveryoption",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="delivery_options",
            field=models.ManyToManyField(
                blank=True,
                help_text="Delivery methods this product can ship with. Blank allows every active option.",
                related_name="products",
                to="store.deliveryoption",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_digital",
            field=models.BooleanField(
                default=False,
                help_text="Delivered digitally. Orders with only digital items skip delivery.",
            ),
        ),
    ]
