"""Fail closed when a deployed Worker still has local development config.

``wrangler dev`` runs the build with ``WRANGLER_COMMAND=dev`` and may keep
localhost and the placeholder D1 id. ``wrangler deploy`` and
``wrangler versions upload`` do not. The Worker bundle only includes ``src/``,
so the build writes ``worker_boot_embed.py`` with the database id and the
command that started it. Production hosts and secrets are not guessed here.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from urllib.parse import urlparse

# Defaults in settings.py. `.dev.vars.example` is unioned in when it is readable.
SETTINGS_DEV_SECRET_KEY = "chili-platform-dev-secret-change-me"
SETTINGS_DEV_OPS_TOKEN = "chili-dev-ops-token"
PLACEHOLDER_D1_DATABASE_ID = "00000000-0000-0000-0000-000000000001"

_DATABASE_ID = re.compile(r'"database_id"\s*:\s*"([^"]*)"')
_LOCAL_HOSTS = {"*", "localhost", "127.0.0.1", "::1", "0.0.0.0"}


def parse_dev_vars(text: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def dev_defaults_from_example(text: str | None) -> tuple[frozenset[str], frozenset[str]]:
    """Secret key and ops token values that must not boot a deployed Worker."""
    secrets = {SETTINGS_DEV_SECRET_KEY}
    tokens = {SETTINGS_DEV_OPS_TOKEN}
    if text:
        parsed = parse_dev_vars(text)
        secret = parsed.get("DJANGO_SECRET_KEY", "").strip()
        token = parsed.get("OPS_TOKEN", "").strip()
        if secret:
            secrets.add(secret)
        if token:
            tokens.add(token)
    return frozenset(secrets), frozenset(tokens)


def parse_d1_database_id(wrangler_text: str) -> str | None:
    match = _DATABASE_ID.search(wrangler_text)
    if match is None:
        return None
    return match.group(1)


def host_token(value: str) -> str:
    text = value.strip()
    if text == "*":
        return "*"
    if "://" in text:
        hostname = urlparse(text).hostname or ""
        return hostname.lower().rstrip(".")
    host = text.lower().rstrip(".")
    if host.startswith("."):
        host = host[1:]
    if host.startswith("[") and "]" in host:
        return host[1 : host.index("]")]
    return host.split("/")[0].split(":")[0]


def is_local_or_wildcard(value: str) -> bool:
    """True for localhost, loopback, or Django's allow-all host."""
    host = host_token(value)
    if host in _LOCAL_HOSTS:
        return True
    return host.endswith(".localhost")


def worker_boot_problems(
    *,
    on_workers: bool,
    wrangler_command: str,
    secret_key: str,
    ops_token: str,
    dev_secret_keys: frozenset[str],
    dev_ops_tokens: frozenset[str],
    allowed_hosts: list[str],
    cors_origins: list[str],
    checkout_urls: dict[str, str],
    public_base_url: str,
    d1_database_id: str | None,
) -> list[str]:
    """Problems that should stop a deployed Worker. Local dev and SQLite return none."""
    if not on_workers or wrangler_command == "dev":
        return []

    problems: list[str] = []
    if secret_key.strip() in dev_secret_keys:
        problems.append(
            "DJANGO_SECRET_KEY is still a dev default from settings or .dev.vars.example."
        )
    if ops_token.strip() in dev_ops_tokens:
        problems.append("OPS_TOKEN is still a dev default from settings or .dev.vars.example.")

    for host in allowed_hosts:
        if is_local_or_wildcard(host):
            problems.append(f"DJANGO_ALLOWED_HOSTS still contains {host!r}.")
    for origin in cors_origins:
        if is_local_or_wildcard(origin):
            problems.append(f"CORS_ALLOWED_ORIGINS still contains {origin!r}.")
    for name, url in checkout_urls.items():
        if is_local_or_wildcard(url):
            problems.append(f"{name} still points at {url!r}.")
    if is_local_or_wildcard(public_base_url):
        problems.append(f"PUBLIC_BASE_URL still points at {public_base_url!r}.")

    if d1_database_id is None or d1_database_id.strip() == "":
        problems.append("D1 database_id is missing from wrangler.jsonc.")
    elif d1_database_id.strip() == PLACEHOLDER_D1_DATABASE_ID:
        problems.append(f"D1 database_id is still the placeholder {PLACEHOLDER_D1_DATABASE_ID}.")
    return problems


def _tuple_literal(values: frozenset[str]) -> str:
    items = ", ".join(repr(item) for item in sorted(values))
    if len(values) == 1:
        items += ","
    return f"({items})"


def render_worker_boot_embed(
    *,
    d1_database_id: str,
    wrangler_command: str,
    dev_secret_keys: frozenset[str],
    dev_ops_tokens: frozenset[str],
) -> str:
    return "\n".join(
        [
            '"""Generated by scripts/embed_worker_boot.py. Do not edit."""',
            f"D1_DATABASE_ID = {d1_database_id!r}",
            f"WRANGLER_COMMAND = {wrangler_command!r}",
            f"DEV_SECRET_KEYS = {_tuple_literal(dev_secret_keys)}",
            f"DEV_OPS_TOKENS = {_tuple_literal(dev_ops_tokens)}",
            "",
        ]
    )


def write_worker_boot_embed(root: Path, wrangler_command: str | None = None) -> Path:
    if wrangler_command is None:
        command = os.environ.get("WRANGLER_COMMAND", "")
    else:
        command = wrangler_command
    wrangler_text = (root / "wrangler.jsonc").read_text()
    example_path = root / ".dev.vars.example"
    example_text = example_path.read_text() if example_path.is_file() else None
    database_id = parse_d1_database_id(wrangler_text) or ""
    secrets, tokens = dev_defaults_from_example(example_text)
    destination = root / "src" / "app" / "worker_boot_embed.py"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        render_worker_boot_embed(
            d1_database_id=database_id,
            wrangler_command=command,
            dev_secret_keys=secrets,
            dev_ops_tokens=tokens,
        )
    )
    return destination


def _load_embed():
    import importlib

    from django.core.exceptions import ImproperlyConfigured

    try:
        return importlib.import_module("app.worker_boot_embed")
    except ImportError as exc:
        raise ImproperlyConfigured(
            "Refusing to boot on the Worker: boot facts were not generated from "
            "wrangler.jsonc. The Worker build must run scripts/embed_worker_boot.py."
        ) from exc


def enforce_worker_boot(
    *,
    secret_key: str,
    ops_token: str,
    allowed_hosts: list[str],
    cors_origins: list[str],
    checkout_urls: dict[str, str],
    public_base_url: str,
    embed: object | None = None,
) -> None:
    """Raise if this process is a deployed Worker still using local config."""
    from django.core.exceptions import ImproperlyConfigured

    loaded = _load_embed() if embed is None else embed
    command = str(getattr(loaded, "WRANGLER_COMMAND", "") or "")
    database_id = getattr(loaded, "D1_DATABASE_ID", None)
    secrets = frozenset(getattr(loaded, "DEV_SECRET_KEYS", ())) | {SETTINGS_DEV_SECRET_KEY}
    tokens = frozenset(getattr(loaded, "DEV_OPS_TOKENS", ())) | {SETTINGS_DEV_OPS_TOKEN}
    problems = worker_boot_problems(
        on_workers=True,
        wrangler_command=command,
        secret_key=secret_key,
        ops_token=ops_token,
        dev_secret_keys=frozenset(secrets),
        dev_ops_tokens=frozenset(tokens),
        allowed_hosts=allowed_hosts,
        cors_origins=cors_origins,
        checkout_urls=checkout_urls,
        public_base_url=public_base_url,
        d1_database_id=None if database_id is None else str(database_id),
    )
    if not problems:
        return
    detail = "\n".join(f"- {item}" for item in problems)
    raise ImproperlyConfigured(
        "Refusing to boot on the Worker until production config is set.\n" + detail
    )
